# Config file for automatic testing at travis-ci.org

dist: trusty

language: java

addons:
  apt:
    packages:
      - openjdk-8-jdk

jdk:
  - openjdk8
  - oraclejdk8

git:
  depth: 4

sudo: false

cache:
  directories:
  - $HOME/.m2

